// yt-tools.js: helpers installed on a YouTube watch tab in the built-in browser. Everything is silent by construction.
window.__quiet = () => { const p=document.querySelector('#movie_player'); try{ p&&p.mute&&p.mute(); }catch(e){} document.querySelectorAll('video').forEach(v=>{ if(!window.__audioGraph){ v.muted=true; v.volume=0; } }); return 1; };
window.__quiet();
document.querySelectorAll('video').forEach(v=>{ try{v.pause()}catch(e){} });
window.__ttUrls = window.__ttUrls || [];
if(!window.__patched){ window.__patched=1; const oo=XMLHttpRequest.prototype.open; XMLHttpRequest.prototype.open=function(m,u){ if(String(u).includes('timedtext')) window.__ttUrls.push(String(u)); return oo.apply(this,arguments); }; const of=window.fetch; window.fetch=function(u,o){ const s=typeof u==='string'?u:(u&&u.url); if(s&&s.includes('timedtext')) window.__ttUrls.push(s); return of.apply(this,arguments); }; }
window.__v = () => document.querySelector('video');
window.__frame = (t) => new Promise(res => { const v=__v(); if(!v) return res(-1); const to=setTimeout(()=>res(-1),8000); v.addEventListener('seeked',()=>{clearTimeout(to); requestAnimationFrame(()=>res(v.currentTime));},{once:true}); v.currentTime=t; try{v.pause()}catch(e){} });
window.__skipAd = () => { const b=document.querySelector('.ytp-skip-ad-button, .ytp-ad-skip-button, .ytp-ad-skip-button-modern'); if(b){b.click(); return 'skipped'} return document.querySelector('.ad-showing')?'ad':'none'; };
if(!document.getElementById('__hide')){ const s=document.createElement('style'); s.id='__hide'; s.textContent='#masthead-container,ytd-masthead{display:none!important} .ytp-chrome-bottom,.ytp-chrome-top,.ytp-gradient-bottom,.ytp-gradient-top,.ytp-ce-element,.ytp-cards-button,.ytp-paid-content-overlay,.ytp-pause-overlay{display:none!important}'; document.head.appendChild(s); }
// captions as cues
window.__cues = async () => { if(window.__cueCache) return window.__cueCache; let url=(window.__ttUrls.find(u=>u.includes('fmt=json3'))||window.__ttUrls[0]); if(!url){ const e=performance.getEntriesByType('resource').map(x=>x.name).filter(n=>n.includes('timedtext')); url=e[0]; } if(!url){ const cc=document.querySelector('.ytp-subtitles-button'); if(cc){ cc.click(); await new Promise(r=>setTimeout(r,1500)); if(cc.getAttribute('aria-pressed')==='true') cc.click(); } url=(window.__ttUrls[0]||performance.getEntriesByType('resource').map(x=>x.name).filter(n=>n.includes('timedtext'))[0]); } if(!url) return null; if(!url.includes('fmt=json3')) url+='&fmt=json3'; const j=await fetch(url).then(r=>r.json()); const ev=(j.events||[]).filter(e=>e.segs); window.__cueCache=ev.map(e=>({t:e.tStartMs/1000, d:(e.dDurationMs||0)/1000, s:e.segs.map(x=>x.utf8).join('').replace(/\n/g,' ').trim()})).filter(l=>l.s); return window.__cueCache; };
// shot detection by frame differencing on a tiny canvas (needs an untainted video: MSE blobs are same-origin)
window.__scan = async (from, to, step=0.5) => { const v=__v(); const W=48,H=27; const c=document.createElement('canvas'); c.width=W; c.height=H; const x=c.getContext('2d',{willReadFrequently:true}); let prev=null; const rows=[]; for(let t=from;t<=to;t+=step){ const got=await __frame(t); if(got<0){ rows.push({t,err:1}); continue; } x.drawImage(v,0,0,W,H); const d=x.getImageData(0,0,W,H).data; let lum=0, diff=0, r=0,g=0,b=0; for(let i=0;i<d.length;i+=4){ const l=(d[i]*0.299+d[i+1]*0.587+d[i+2]*0.114); lum+=l; r+=d[i]; g+=d[i+1]; b+=d[i+2]; if(prev){ diff+=Math.abs(d[i]-prev[i])+Math.abs(d[i+1]-prev[i+1])+Math.abs(d[i+2]-prev[i+2]); } } const n=d.length/4; rows.push({t:+t.toFixed(2), lum:+(lum/n/255).toFixed(3), diff: prev? +(diff/n/3/255).toFixed(3):0, rgb:[Math.round(r/n),Math.round(g/n),Math.round(b/n)]}); prev=new Uint8ClampedArray(d); } window.__scanRows=(window.__scanRows||[]).concat(rows); return rows.length; };
window.__shots = (cut=0.18, rows=window.__scanRows) => { const shots=[]; let cur={start:rows[0].t, lums:[], diffs:[], rgb:[0,0,0], n:0}; for(let i=1;i<rows.length;i++){ const r=rows[i]; if(r.diff>=cut){ cur.end=r.t; shots.push(cur); cur={start:r.t, lums:[], diffs:[], rgb:[0,0,0], n:0}; } cur.lums.push(r.lum); cur.diffs.push(r.diff<cut?r.diff:0); cur.rgb=[cur.rgb[0]+r.rgb[0],cur.rgb[1]+r.rgb[1],cur.rgb[2]+r.rgb[2]]; cur.n++; } cur.end=rows[rows.length-1].t; shots.push(cur); return shots.map(s=>({start:s.start, dur:+(s.end-s.start).toFixed(1), lum:+(s.lums.reduce((a,b)=>a+b,0)/Math.max(1,s.lums.length)).toFixed(2), motion:+(s.diffs.reduce((a,b)=>a+b,0)/Math.max(1,s.diffs.length)).toFixed(3), rgb:s.rgb.map(v=>Math.round(v/Math.max(1,s.n)))})); };
// montage: draws frames at given times into a grid canvas fixed over the page, with timestamps, so one screenshot shows many shots
window.__montage = async (times, cols=6, w=300, h=169) => { const v=__v(); let c=document.getElementById('__mont'); if(!c){ c=document.createElement('canvas'); c.id='__mont'; c.style.cssText='position:fixed;left:0;top:0;z-index:999999;background:#222'; document.body.appendChild(c); } const rows=Math.ceil(times.length/cols); c.width=cols*w; c.height=rows*(h+18); const x=c.getContext('2d'); x.fillStyle='#222'; x.fillRect(0,0,c.width,c.height); x.font='bold 14px monospace'; for(let i=0;i<times.length;i++){ const t=times[i]; const got=await __frame(t); const cx=(i%cols)*w, cy=Math.floor(i/cols)*(h+18); if(got>=0) x.drawImage(v,cx,cy,w,h); x.fillStyle='#ff0'; x.fillText(`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}.${Math.round((t%1)*10)}`, cx+4, cy+h+14); } return {w:c.width,h:c.height}; };
window.__montageHide = () => { const c=document.getElementById('__mont'); if(c) c.style.display='none'; };
window.__montageShow = () => { const c=document.getElementById('__mont'); if(c) c.style.display='block'; };
// audio: silent by construction. The element's output is routed into a graph whose last node is a gain at 0; nothing reaches the speakers.
window.__audioStart = () => { const v=__v(); if(window.__audioGraph) return 'exists'; const ctx=new (window.AudioContext||window.webkitAudioContext)(); const src=ctx.createMediaElementSource(v); const an=ctx.createAnalyser(); an.fftSize=2048; an.smoothingTimeConstant=0; const gain=ctx.createGain(); gain.gain.value=0; src.connect(an); an.connect(gain); gain.connect(ctx.destination); window.__audioGraph={ctx,src,an,gain}; return {state:ctx.state, gain:gain.gain.value}; };
window.__audioRun = (from, to, rate=2, hop=0.1) => new Promise(async (res) => { const v=__v(); const g=window.__audioGraph; if(!g) return res({err:'no graph'}); if(g.gain.gain.value!==0) return res({err:'gain not zero, refusing'}); await g.ctx.resume(); await __frame(from); v.playbackRate=rate; v.muted=false; v.volume=1; const td=new Float32Array(g.an.fftSize), fd=new Float32Array(g.an.frequencyBinCount); const out=[]; let last=-1; const tick=()=>{ const t=v.currentTime; if(t>=to||v.paused||v.ended){ v.pause(); v.muted=true; v.volume=0; v.playbackRate=1; window.__audioRows=(window.__audioRows||[]).concat(out); return res({rows:out.length, from, to}); } if(t-last>=hop){ last=t; g.an.getFloatTimeDomainData(td); let s=0; for(let i=0;i<td.length;i++) s+=td[i]*td[i]; const rms=Math.sqrt(s/td.length); g.an.getFloatFrequencyData(fd); const sr=g.ctx.sampleRate, nb=fd.length; let num=0, den=0, low=0, mid=0, hi=0; for(let i=1;i<nb;i++){ const m=Math.pow(10,fd[i]/20); const f=i*sr/2/nb; num+=f*m; den+=m; if(f<200) low+=m; else if(f<4000) mid+=m; else hi+=m; } out.push({t:+t.toFixed(2), rms:+rms.toFixed(4), cent:den?Math.round(num/den):0, low:+(low/(den||1)).toFixed(3), hi:+(hi/(den||1)).toFixed(3)}); } requestAnimationFrame(tick); }; v.play().then(()=>requestAnimationFrame(tick)).catch(e=>res({err:String(e)})); });
window.__audioStats = (rows=window.__audioRows, cues=window.__cueCache) => { if(!rows||!rows.length) return null; const r=rows.map(x=>x.rms).filter(x=>x>0).sort((a,b)=>a-b); const floor=r[Math.floor(r.length*0.1)]||0.001; const speech=floor*4; let pauses=[], cur=null; for(const x of rows){ if(x.rms<speech){ if(!cur) cur={start:x.t}; cur.end=x.t; } else if(cur){ if(cur.end-cur.start>=0.3) pauses.push({t:cur.start, d:+(cur.end-cur.start).toFixed(2)}); cur=null; } } const med=r[Math.floor(r.length/2)], p90=r[Math.floor(r.length*0.9)], p99=r[Math.floor(r.length*0.99)]; let perCue=null; if(cues){ perCue=cues.filter(c=>c.t>=rows[0].t&&c.t<=rows[rows.length-1].t).map(c=>{ const w=rows.filter(x=>x.t>=c.t&&x.t<c.t+c.d); const m=w.length? w.reduce((a,b)=>a+b.rms,0)/w.length:0; const pk=w.length? Math.max(...w.map(x=>x.rms)):0; const ce=w.length? Math.round(w.reduce((a,b)=>a+b.cent,0)/w.length):0; return {t:c.t, s:c.s.slice(0,60), rms:+m.toFixed(4), peak:+pk.toFixed(4), cent:ce}; }); } return {n:rows.length, floor:+floor.toFixed(4), median:+med.toFixed(4), p90:+p90.toFixed(4), p99:+p99.toFixed(4), dynamicRangeDb:+(20*Math.log10(p99/Math.max(floor,1e-5))).toFixed(1), pauses:pauses.length, pauseSeconds:+pauses.reduce((a,b)=>a+b.d,0).toFixed(1), longestPause:pauses.sort((a,b)=>b.d-a.d).slice(0,8), perCue}; };
'tools installed';
